numero = int (input('Digite um número '))
dobro = (numero * 2)
triplo = (numero * 3)
raiz = (numero ** (1/2))
print('Número : {} \nDobro : {} \nTriplo : {}\nRaiz : {}'.format (numero, dobro, triplo, raiz))
