numero = int (input ('Digite um número : '))
x_1 = (numero * 1)
x_2 = (numero * 2)
x_3 = (numero * 3)
x_4 = (numero * 4)
x_5 = (numero * 5)
x_6 = (numero * 6)
x_7 = (numero * 7)
x_8 = (numero * 8)
x_9 = (numero * 9)
x_10 = (numero * 10)
print ('A tabuada de {} é : \n{} \n{} \n{} \n{} \n{} \n{} \n{} \n{} \n{} \n{}'.format(numero, x_1 ,x_2 ,x_3 ,x_4 ,x_5 ,x_6 ,x_7 ,x_8 ,x_9 ,x_10))
